#!/bin/bash
export COMMAND_PREFIX="cmd-"

IMAGE_NAME="zwave"
# added leading slash for cygwin support
VOLUME="/${PWD}:/go/src/github.com/shayne/zwave"
PROJ_DIR="/go/src/github.com/shayne/zwave"
BUILD_DIR="${PROJ_DIR}/build"
CMD_DIR="${PROJ_DIR}/cmd/shell"
DOCKER_RUN_CMD="docker run --rm -it -v $VOLUME $IMAGE_NAME"

# build deploy and run
function cmd-all {
  shake build
  shake deploy
  shake run
}

# cross-compile go app in docker container (out: build/zwave)
function cmd-build {
  $DOCKER_RUN_CMD bash -c "cd $BUILD_DIR && go build -v ../cmd/shell"
}

# generate go-openzwave code from openzwave headers
function cmd-make-deps {
  $DOCKER_RUN_CMD bash -c "cd ${PROJ_DIR}/go-openzwave && make deps"
}

# deploy to raspberrypi
function cmd-deploy {
  scp build/shell raspberrypi:
}

# run on raspberrypi
function cmd-run {
  ssh -t raspberrypi ./shell
}

function cmd-docker-build {
  docker build -t "$IMAGE_NAME" .
}
